export const actions = {
    GET_CITY: 'GET_CITY',
    GET_WEATHER: 'GET_WEATHER',
    RES_GET_CITY: 'RES_GET_CITY',
    RES_GET_WEATHER: 'RES_GET_WEATHER',
    CLEAR_CITY: 'CLEAR_CITY',
    IS_FETCHING: 'IS_FETCHING',
    FETCHING_DONE: 'FETCHING_DONE',
    SET_CUREENT_CITY: 'SET_CUREENT_CITY',
    ERROR: 'ERROR'
}